version: "2"

services:
  python:
    image: python:2.7.16-stretch
    container_name: aliens_world
#    restart: always
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/share/zoneinfo/Europe/London:/etc/localtime
      - /home/dennys/.config/google-chrome
    entrypoint: sh install.sh
    networks:
      - aliens
networks:
  aliens:
    driver: bridge